<?php
use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;


/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
function simple_analytics_custom_page_attachments(array &$page) {
    \Drupal::service('page_cache_kill_switch')->trigger();
  $config = \Drupal::config('simple_analytics_custom.settings');
  $dataSaGlobal = $config->get('data_sa_global');
  $dataFullUrl = $config->get('data_full_urls');
  $ignoreAdmins = $config->get('ignore_admin');
  $dataTitle = $config->get('data_use_title');
  $enabled = $config->get('enabling');
  $emailClicks = $config->get('email_clicks');
  $download = $config->get('downloads');
  $outbound = $config->get('outbound_links');
  $dataExtension = $config->get('data_extension');
  $extent = '';
  if(isset($extent)){
    $extent = implode(", ",$dataExtension);
  }
  
$adminIgnore = false;
if($ignoreAdmins == 1){
  $roles = \Drupal::currentUser()->getRoles();
  if (in_array('administrator', $roles)) {
    $adminIgnore = true;
  }  
}

if($adminIgnore != true){
if($enabled == 1){
/* Event Script */
if($dataSaGlobal){
    $script = 'window.'.$dataSaGlobal.'||function(){var a=[].slice.call(arguments);window.'.$dataSaGlobal.'.q?window.'.$dataSaGlobal.'.q.push(a):window.'.$dataSaGlobal.'.q=[a]};';
  }else{
      $script = 'window.sa_event=window.sa_event||function(){var a=[].slice.call(arguments);window.sa_event.q?window.sa_event.q.push(a):window.sa_event.q=[a]};';
      $script .= 'function saLoaded(){if (window.sa_pageview) window.sa_pageview(window.location.pathname)};';
  }
  $page['#attached']['html_head']['data_global'] = [
      [
        '#tag' => 'script',
        '#attributes' => [
          'type' => 'text/javascript',
        ],
       '#value' => \Drupal\Core\Render\Markup::create($script),
      ], 
       'data_global_snippet',
    ];
  if($emailClicks == 1){
     $page['#attached']['html_head']['script_event_mode'] = [
           [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "emails",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
         'event_mode_script',
       ]; 
  }
  if($download == 1){
     $page['#attached']['html_head']['script_event_mode'] = [
           [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "downloads",
                      'data-extensions'=> "$extent",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
         'event_mode_script',
        ];  
  }
  if($outbound == 1){
     $page['#attached']['html_head']['script_event_mode'] = [
           [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "outbound",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
         'event_mode_script',
        ];  
  }
  if($outbound==1 && $emailClicks==1){
       $page['#attached']['html_head']['script_event_mode'] = [
        [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "outbound,emails",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
        'event_mode_script',
      ];
  }
  if($outbound==1 && $download==1){
       $page['#attached']['html_head']['script_event_mode'] = [
        [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "outbound,downloads",
                      'data-extensions'=> "$extent",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
        'event_mode_script',
      ];
  }
  if($emailClicks==1 && $download==1){
       $page['#attached']['html_head']['script_event_mode'] = [
        [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "emails,downloads",
                      'data-extensions'=> "$extent",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
        'event_mode_script',
      ];
  }
  if($outbound==1 && $emailClicks==1 && $download==1){
       $page['#attached']['html_head']['script_event_mode'] = [
        [
             '#tag' => 'script',
             '#attributes' => [
                     'data-collect'=> "outbound,emails,downloads",
                      'data-extensions'=> "$extent",
                      'data-use-title'=> "$dataTitle",
                      'data-full-urls'=> "$dataFullUrl",
                      'async' => TRUE,
                      'src' => 'https://scripts.simpleanalyticscdn.com/auto-events.js'
                  ]
        ],
        'event_mode_script',
      ];
  }

 }
}

}
function simple_analytics_custom_page_top(array &$page_top) {
    \Drupal::service('page_cache_kill_switch')->trigger();
  $config = \Drupal::config('simple_analytics_custom.settings');
  $customDomains = $config->get('overwrite_domain');
  $dataMode = $config->get('hash_mode');
  $ignorePages = $config->get('data_ignore_pages');
  $ignoreAdmins = $config->get('ignore_admin');
  $dataCollectDntTrack = $config->get('do_not_track_visits');
  $dataAutoCollectView = $config->get('collect_page_views');
  $enabled = $config->get('enabling');
  $automatedEvents = $config->get('collected_automated_events');
  $extraSettings = $config->get('extrasettings');
  $dataSaGlobal = $config->get('data_sa_global');
   $sub_script =  '';
    $extra = unserialize($extraSettings);
     if(is_array($extra)) {
    foreach ($extra as $key => $value) {
      $extraKey = $value['key'];
      $extraValue = $value['value'];
    }
  }
$page_top['page_top'] = [];
$adminIgnore = false;
if($ignoreAdmins == 1){
  $roles = \Drupal::currentUser()->getRoles();
  if (in_array('administrator', $roles)) {
    $adminIgnore = true;
  }  
}

if($adminIgnore != true){
if($enabled == 1){
   if($dataMode == 1){
        $sub_script .= 'data-mode="hash" '; 
   }
   if(!empty($dataSaGlobal)){
     $sub_script .= 'data-sa-global="'.$dataSaGlobal.'" ';
   }
   if(!empty($dataAutoCollectView)){
     $sub_script .= 'data-auto-collect="true"';
   }
   if(!empty($dataCollectDntTrack)){
     $sub_script .= 'data-collect-dnt="'.$dataCollectDntTrack.'" ';
   }
   if(!empty($ignorePages)){
     $sub_script .= 'data-ignore-pages="'.$ignorePages.'" ';
   }
   if(!empty($extraKey)){
     $sub_script .= $extraKey;
   }
   if(!empty($extraValue)){
     $sub_script .= ' = "'.$extraValue.'" ';
   }
   $collectionScripts = '';
   if($dataAutoCollectView == 0){
    $collectionScripts .= '<script>function saLoaded(){if (window.sa_pageview) window.sa_pageview(window.location.pathname)};</script>';
     $collectionScripts .= '<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>';
     $sub_script .= 'onload="saLoaded()"';
     $sub_script .= 'data-auto-collect="false" ';
   }
  $autoscript_tag_markup = '';
  if($automatedEvents == 1){
  $autoscript_tag_markup = '<script ' .$sub_script. ' async defer src=https://scripts.simpleanalyticscdn.com/plus.js ></script>';
  }elseif($customDomains){
  $noscript_tag_markup = '<script ' .$sub_script. ' async defer src=https://'.$customDomains.'/latest.js></script>';
  $noscript_tag_markup .= '<noscript><img src="https://'.$customDomains.'/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade"/></noscript>';
    if(isset($noscript_tag_markup)){
       $page_top['page_top'][]['#markup'] =  Markup::create($noscript_tag_markup);
    }
  }else{
    $embed_script = '<script ' .$sub_script. ' async defer src=https://scripts.simpleanalyticscdn.com/latest.js></script>';
    if(isset($embed_script)){
       $page_top['page_top'][]['#markup'] =  Markup::create($embed_script);
    }
  }
    if(isset($autoscript_tag_markup)){
       $page_top['page_top']['#markup'] =  Markup::create($autoscript_tag_markup);
    } 
    if (!empty($collectionScripts)) {
       $page_top['page_top'][]['#markup'] =  Markup::create($collectionScripts);
    }
 }
}
}
